language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.1.6.0
env:
  - LONG_RUN=true
matrix:
  include:
    - rvm: 2.0
      gemfile: Gemfile_ruby2
    - rvm: 2.1
      gemfile: Gemfile_ruby2
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.6.0
bundler_args: --without local_development
